export const IPC_CHANNELS = {
  appInfo: 'app:info',
  platform: 'system:platform',
  systemStatus: 'system:status',
  runtimeStatus: 'runtime:status',
  runtimeManifest: 'runtime:manifest',
  runtimeInstall: 'runtime:install',
  runtimeInstallProgress: 'runtime:install-progress',
  runtimeRemove: 'runtime:remove',
  runtimeActivate: 'runtime:activate',
  runtimeOpenFolder: 'runtime:open-folder',
  downloadedModels: 'models:downloaded',
  downloadModel: 'models:download',
  modelDownloadProgress: 'models:download-progress',
  deleteModel: 'models:delete',
  windowIsMaximized: 'window:is-maximized',
  windowStateChanged: 'window:state-changed',
  windowMinimize: 'window:minimize',
  windowMaximize: 'window:maximize',
  windowClose: 'window:close',
  whisperTranscribe: 'whisper:transcribe',
  whisperOutputChunk: 'whisper:output-chunk',
  whisperProgressUpdate: 'whisper:progress-update',
  listTranscriptions: 'transcriptions:list',
  deleteTranscription: 'transcriptions:delete',
  readTextFile: 'fs:read-text-file',
  writeTextFile: 'fs:write-text-file',
  selectDirectory: 'fs:select-directory',
  selectFile: 'fs:select-file',
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  appCheckUpdate: 'app:check-update',
  shellOpenExternal: 'shell:open-external'
} as const

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS]
